substitutions:
  name: 1wire-sensor
  friendly_name: 1Wire Sensor

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

one_wire:
  - platform: gpio
    pin: GPIO22

sensor:
  - platform: dallas_temp
    name: Temperature 1
    address: 0x5500000535b9da28
    update_interval: 60s
  - platform: dallas_temp
    name: Temperature 2
    address: 0x7e00000534bb4328
    update_interval: 60s
  - platform: dallas_temp
    name: Temperature 3
    address: 0x5500000535b9da28
    update_interval: 60s
  - platform: dallas_temp
    name: Temperature 4
    address: 0x7e00000534bb4328
    update_interval: 60s
  - platform: dallas_temp
    name: Temperature 5
    address: 0x5500000535b9da28
    update_interval: 60s
  - platform: dallas_temp
    name: Temperature 6
    address: 0x7e00000534bb4328
    update_interval: 60s
